-- CreateTable
CREATE TABLE "user" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "gender" BOOL NOT NULL DEFAULT true,
    "email" STRING NOT NULL,
    "contact" STRING,
    "password" STRING NOT NULL,
    "profile" STRING,
    "birth_date" DATE NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "active" BOOL NOT NULL DEFAULT false,

    CONSTRAINT "user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "feedback" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "desc" STRING NOT NULL,
    "ownerId" INT4 NOT NULL,

    CONSTRAINT "feedback_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "spa" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "desc" STRING NOT NULL,
    "cover_photo" STRING,
    "display_photo" STRING,
    "email" STRING,
    "contact" STRING,
    "address" STRING,
    "ownerId" INT4,
    "openTime" STRING,
    "closeTime" STRING,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "spa_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "spa_service" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "spaId" INT4 NOT NULL,
    "serviceId" INT4 NOT NULL,

    CONSTRAINT "spa_service_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "spa_product" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "spaId" INT4 NOT NULL,
    "productId" INT4 NOT NULL,

    CONSTRAINT "spa_product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "description" STRING,
    "display_photo" STRING,
    "available" BOOL NOT NULL DEFAULT true,
    "spaId" INT4,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "service_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "description" STRING,
    "display_photo" STRING,
    "available" BOOL NOT NULL DEFAULT true,
    "spaId" INT4,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "product_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "user_email_key" ON "user"("email");

-- AddForeignKey
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "spa" ADD CONSTRAINT "spa_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "spa_service" ADD CONSTRAINT "spa_service_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "service"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "spa_service" ADD CONSTRAINT "spa_service_spaId_fkey" FOREIGN KEY ("spaId") REFERENCES "spa"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "spa_product" ADD CONSTRAINT "spa_product_productId_fkey" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "spa_product" ADD CONSTRAINT "spa_product_spaId_fkey" FOREIGN KEY ("spaId") REFERENCES "spa"("id") ON DELETE CASCADE ON UPDATE CASCADE;
